import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import About from '../components/About'

import Navbar from "../components/Navbar"
import WhatIDo from '../components/WhatIDo'
import Skills from '../components/Skills'
import Work from '../components/Work'
import Contact from '../components/Contact'
import Fotter from '../components/Fotter'
import Sidebar from '../components/Sidebar'
import { useState } from 'react'

export default function Home() {

  const [isOpen, setIsOpen] = useState(false)
  const toggleSidebar = () => {
    setIsOpen(!isOpen)
  }

  return (
    <>
      <div>
      <Head>
        <title>Portofolio Nazar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar toggleSidebar={toggleSidebar} />
      </header>

      <main>
        <Sidebar isOpen={isOpen} toggleSidebar={toggleSidebar} />
        <Hero />
        <About />
        <WhatIDo />
        <Skills />
        <Work />
        <Contact />
        <Fotter />
      </main>
      </div> 
    </>
  )
}
